In [161]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/conda/lib/python3.7/site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.7/site-packages (from openpyxl) (1.1.0)
^C
ERROR: Operation cancelled by user

In [1]:
# Importing packages
import pandas as pd
import math
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [163]:
# Importing Data
df_people = pd.read_csv("../input/temperatureprediction/full occ csv.csv")
df_weather = pd.read_csv("../input/temperatureprediction/weather-1.csv")
df_electricity = pd.read_excel("../input/temperatureprediction/consumption.xlsx")

In [164]:
# Removing unwanted columns
df_electricity = df_electricity.drop(["H","OPTIMA Half Hourly DATA","Unnamed: 2","CHANNEL TYPE","UNITS"],axis = 1)

# Slicing all data into same shape
df_weather = df_weather.iloc[:1535,:]
df_people = df_people.iloc[:1535,:]

In [165]:
# Viewing Dataframe
df_people.head()

,Date,00:00,01:00,02:00,03:00,04:00,05:00,06:00,07:00,08:00,...,14:00,15:00,16:00,17:00,18:00,19:00,20:00,21:00,22:00,23:00
0,01/09/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,225,253,246,209,164,124,NaN,NaN,NaN,NaN
1,02/09/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,189,233,238,242,196,136,NaN,NaN,NaN,NaN
2,03/09/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,222,278,291,274,234,160,NaN,NaN,NaN,NaN
3,04/09/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,305,364,331,303,238,180,NaN,NaN,NaN,NaN
4,05/09/2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,...,261,297,290,279,249,180,NaN,NaN,NaN,NaN

In [166]:
# Viewing Dataframe
df_electricity

,READING DATE,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,19:30,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,23:59:00
0,2017-09-01,1.0,0.8,0.8,0.8,0.7,0.7,0.7,0.8,0.7,...,2.5,2.2,1.1,0.8,0.8,0.7,0.8,0.8,0.7,0.7
1,2017-09-02,0.7,0.7,0.7,0.8,0.7,0.7,0.8,0.6,0.8,...,1.4,1.1,1.0,0.7,0.7,0.8,0.7,0.8,0.6,0.0
2,2017-09-03,0.7,0.6,0.7,0.9,0.8,0.7,0.7,0.7,0.7,...,1.2,1.4,1.0,0.8,0.7,0.8,0.8,0.8,0.7,0.7
3,2017-09-04,0.7,0.8,0.7,0.7,0.7,0.7,0.7,0.7,0.7,...,1.9,1.2,1.0,0.8,1.4,1.1,0.9,0.8,0.8,0.0
4,2017-09-05,0.7,0.7,0.8,0.7,0.7,0.8,0.7,0.7,0.7,...,2.4,2.3,0.9,0.8,0.8,0.8,0.8,0.8,0.7,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,2021-11-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1531,2021-11-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.2,3.3,2.7,2.6,0.0,1.8,1.8,1.8,1.6,1.5
1532,2021-11-11,0.0,1.6,1.4,0.0,1.4,1.3,0.0,1.5,0.9,...,2.7,3.7,3.0,3.2,2.3,1.8,1.7,1.6,0.0,1.7
1533,2021-11-12,1.2,0.0,1.5,1.5,1.2,1.1,1.2,0.9,0.9,...,3.6,2.7,2.7,2.9,1.5,1.4,1.6,1.4,1.4,1.4
1534,2021-11-13,1.2,1.4,1.2,1.2,1.2,2.2,2.2,2.4,1.6,...,1.8,3.1,1.9,2.8,2.7,3.2,1.7,1.4,1.3,1.4

In [167]:
# Viewing Dataframe
df_weather_copy = df_weather.copy()
df_weather.head()

,READING DATE,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,19:30,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,23:59:00
0,2017-09-01,12,12,12,12,12,11,11,11,11,...,15,14,14,13,13,13,13,12,12,12
1,2017-09-02,12,12,12,11,11,11,11,11,11,...,17,16,16,15,15,14,14,14,14,13
2,2017-09-03,13,13,13,12,12,12,12,12,12,...,13,13,13,13,13,13,13,13,13,13
3,2017-09-04,13,14,14,14,14,14,14,14,14,...,18,18,18,17,17,17,17,17,17,17
4,2017-09-05,17,16,16,16,16,16,16,16,16,...,16,15,15,14,14,14,14,13,13,13

In [168]:
df_people[["Date"]] = df_people[["Date"]].apply(pd.to_datetime)
df_electricity["READING DATE"] = df_electricity["READING DATE"].apply(pd.to_datetime)
df_weather["READING DATE"] = df_weather["READING DATE"].apply(pd.to_datetime)

In [169]:
# Making sure both reading date columns are same
df_weather["READING DATE"] = df_electricity["READING DATE"]
df_people["Date"] = df_weather["READING DATE"]
# Filling NAN values with 0
df_people = df_people.fillna(0)

In [170]:
# Dataframe slicing
df_weather_updated = pd.DataFrame()
df_weather_updated["READING DATE"] = df_weather["READING DATE"]
for j,i in enumerate(range(2,50,2)):
  time = ("Weather_"+str(j)+":00")
  df_weather_updated[time] = df_weather.iloc[:,i]

df_electricity_updated = pd.DataFrame()
df_electricity_updated["READING DATE"] = df_electricity["READING DATE"]
for j,i in enumerate(range(2,50,2)):
  time = ("Electricity_"+str(j)+":00")
  df_electricity_updated[time] = df_electricity.iloc[:,i]

df_people_updated = pd.DataFrame()
df_people_updated["READING DATE"] = df_people["Date"]
for j,i in enumerate(range(1,25,1)):
  time = ("People_"+str(j)+":00")
  df_people_updated[time] = df_people.iloc[:,i]

In [171]:
# Updated Dataframe
df_people_updated.head()

,READING DATE,People_0:00,People_1:00,People_2:00,People_3:00,People_4:00,People_5:00,People_6:00,People_7:00,People_8:00,...,People_14:00,People_15:00,People_16:00,People_17:00,People_18:00,People_19:00,People_20:00,People_21:00,People_22:00,People_23:00
0,2017-09-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,225,253,246,209,164,124,0,0,0,0
1,2017-09-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,189,233,238,242,196,136,0,0,0,0
2,2017-09-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,222,278,291,274,234,160,0,0,0,0
3,2017-09-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,305,364,331,303,238,180,0,0,0,0
4,2017-09-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,...,261,297,290,279,249,180,0,0,0,0

In [172]:
df_weather_updated.head()

,READING DATE,Weather_0:00,Weather_1:00,Weather_2:00,Weather_3:00,Weather_4:00,Weather_5:00,Weather_6:00,Weather_7:00,Weather_8:00,...,Weather_14:00,Weather_15:00,Weather_16:00,Weather_17:00,Weather_18:00,Weather_19:00,Weather_20:00,Weather_21:00,Weather_22:00,Weather_23:00
0,2017-09-01,12,12,11,11,11,11,12,13,15,...,18,17,17,16,15,14,13,13,12,12
1,2017-09-02,12,11,11,11,11,10,12,14,15,...,18,18,18,17,17,16,15,14,14,13
2,2017-09-03,13,12,12,12,12,12,13,13,14,...,13,13,13,13,13,13,13,13,13,13
3,2017-09-04,14,14,14,14,14,14,15,15,16,...,21,20,20,19,18,18,17,17,17,17
4,2017-09-05,16,16,16,16,16,16,16,16,16,...,18,18,17,17,16,15,14,14,13,13

In [173]:
print("Weather Dataset Size",df_weather_updated.shape)
print("Electricity Dataset Size",df_electricity_updated.shape)
print("people Dataset Size",df_people_updated.shape)

Weather Dataset Size (1535, 25)
Electricity Dataset Size (1535, 25)
people Dataset Size (1535, 25)

In [174]:
# Dropping Data Column
df_weather = df_weather_updated.drop(["READING DATE"],axis =1)
df_electricity = df_electricity_updated.drop(["READING DATE"],axis =1)
df_electricity = df_electricity.fillna(method='ffill')
df_people = df_people_updated.drop(["READING DATE"],axis =1)

In [175]:
# Replacing outlier values
for i,j in enumerate(df_people["People_13:00"]):
  if j == 'UID card access problems':
    df_people["People_13:00"][i] = np.nan

for k in df_people.columns:
  for i,j in enumerate(df_people[k]):
    if j == 'Sentry Juno installation - Sentry offline, no data 9th -22nd July' or j == 'Sentry Juno live but no data yet' or j == "Sentry Juno put into offline mode" or j == "#" or j == " ":
      df_people[k][i] = np.nan

df_people = df_people.fillna(method='ffill')

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [176]:
# Merging all dataframes
df_final = pd.DataFrame()
j = 0
k = 0
l = 0
m = 0
for i in range(72):
  if i in range(0,72,3):
    df_final[i] = df_weather.iloc[:,k]
    k = k+1
  if i in range(1,72,3):
    df_final[i] = df_electricity.iloc[:,l]
    l = l+1
  if i  in range(2,72,3):
    df_final[i] =df_people.iloc[:,m]
    m = m+1

In [177]:
# Slicing X, Y
X = df_electricity.values.ravel().reshape(-1,1)
Y = df_electricity.values.ravel()

In [178]:
# Slicing train data i.e. 80% of total data
training_data_len = math.ceil(len(X) * .96254)

# Applying scaling
scaler_close = MinMaxScaler(feature_range=(0, 1))
scaled_data_close = scaler_close.fit_transform(X)

# Slicing
X_train_scaled = scaled_data_close[0:training_data_len, :]
Y_train_len = Y[0:training_data_len]

# Creating X_train, Y_train using for loop with 60 window size
x_train = []
y_train = []
for i in range(60, len(X_train_scaled)):
    x_train.append(X_train_scaled [i-60:i, 0])
    y_train.append(Y_train_len[i])
    if i <= 61:
        print(x_train)
        print(y_train)
        
# COnverting them to array and reshape
x_train, y_train = np.array(x_train), np.array(y_train)       
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

[array([0.00062868, 0.00062868, 0.0005501 , 0.00062868, 0.00062868,
       0.0005501 , 0.00062868, 0.00133595, 0.00220039, 0.00259332,
       0.00235756, 0.00282908, 0.00290766, 0.00251473, 0.00267191,
       0.00259332, 0.00251473, 0.00212181, 0.00212181, 0.00172888,
       0.00062868, 0.0005501 , 0.00062868, 0.0005501 , 0.0005501 ,
       0.00062868, 0.0005501 , 0.00047151, 0.00047151, 0.00125737,
       0.00149312, 0.0005501 , 0.00117878, 0.00078585, 0.00133595,
       0.00125737, 0.00172888, 0.00117878, 0.00125737, 0.00141454,
       0.00117878, 0.0011002 , 0.00094303, 0.00086444, 0.0005501 ,
       0.00062868, 0.00062868, 0.        , 0.00047151, 0.00070727,
       0.0005501 , 0.0005501 , 0.0005501 , 0.00141454, 0.0005501 ,
       0.0005501 , 0.00133595, 0.0011002 , 0.00188605, 0.00117878])]
[2.1]
[array([0.00062868, 0.00062868, 0.0005501 , 0.00062868, 0.00062868,
       0.0005501 , 0.00062868, 0.00133595, 0.00220039, 0.00259332,
       0.00235756, 0.00282908, 0.00290766, 0.00251473, 0.00267191,
       0.00259332, 0.00251473, 0.00212181, 0.00212181, 0.00172888,
       0.00062868, 0.0005501 , 0.00062868, 0.0005501 , 0.0005501 ,
       0.00062868, 0.0005501 , 0.00047151, 0.00047151, 0.00125737,
       0.00149312, 0.0005501 , 0.00117878, 0.00078585, 0.00133595,
       0.00125737, 0.00172888, 0.00117878, 0.00125737, 0.00141454,
       0.00117878, 0.0011002 , 0.00094303, 0.00086444, 0.0005501 ,
       0.00062868, 0.00062868, 0.        , 0.00047151, 0.00070727,
       0.0005501 , 0.0005501 , 0.0005501 , 0.00141454, 0.0005501 ,
       0.0005501 , 0.00133595, 0.0011002 , 0.00188605, 0.00117878]), array([0.00062868, 0.0005501 , 0.00062868, 0.00062868, 0.0005501 ,
       0.00062868, 0.00133595, 0.00220039, 0.00259332, 0.00235756,
       0.00282908, 0.00290766, 0.00251473, 0.00267191, 0.00259332,
       0.00251473, 0.00212181, 0.00212181, 0.00172888, 0.00062868,
       0.0005501 , 0.00062868, 0.0005501 , 0.0005501 , 0.00062868,
       0.0005501 , 0.00047151, 0.00047151, 0.00125737, 0.00149312,
       0.0005501 , 0.00117878, 0.00078585, 0.00133595, 0.00125737,
       0.00172888, 0.00117878, 0.00125737, 0.00141454, 0.00117878,
       0.0011002 , 0.00094303, 0.00086444, 0.0005501 , 0.00062868,
       0.00062868, 0.        , 0.00047151, 0.00070727, 0.0005501 ,
       0.0005501 , 0.0005501 , 0.00141454, 0.0005501 , 0.0005501 ,
       0.00133595, 0.0011002 , 0.00188605, 0.00117878, 0.00165029])]
[2.1, 2.3]

In [179]:
# LSTM Model
model = Sequential()
model.add(LSTM(128, return_sequences=True ,input_shape=(x_train.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(88, return_sequences=True))
model.add(LSTM(48, return_sequences=False))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='linear'))

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)

# Compiling the model
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [180]:
# Fiiting data into model
model.fit(x_train, y_train, batch_size=512, epochs=200)

Epoch 1/200
70/70 [==============================] - 5s 22ms/step - loss: 4.9841
Epoch 2/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4846
Epoch 3/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4730
Epoch 4/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4673
Epoch 5/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4587
Epoch 6/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4581
Epoch 7/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4559
Epoch 8/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4543
Epoch 9/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4575
Epoch 10/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4538
Epoch 11/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4510
Epoch 12/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4534
Epoch 13/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4522
Epoch 14/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4486
Epoch 15/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4481
Epoch 16/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4462
Epoch 17/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4489
Epoch 18/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4476
Epoch 19/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4467
Epoch 20/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4423
Epoch 21/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4472
Epoch 22/200
70/70 [==============================] - 2s 23ms/step - loss: 1.4459
Epoch 23/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4469
Epoch 24/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4452
Epoch 25/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4460
Epoch 26/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4436
Epoch 27/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4448
Epoch 28/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4443
Epoch 29/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4449
Epoch 30/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4445
Epoch 31/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4434
Epoch 32/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4428
Epoch 33/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4455
Epoch 34/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4444
Epoch 35/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4434
Epoch 36/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4456
Epoch 37/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4436
Epoch 38/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4414
Epoch 39/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4441
Epoch 40/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4424
Epoch 41/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4417
Epoch 42/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4410
Epoch 43/200
70/70 [==============================] - 2s 23ms/step - loss: 1.4439
Epoch 44/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4440
Epoch 45/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4430
Epoch 46/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4434
Epoch 47/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4418
Epoch 48/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4420: 1
Epoch 49/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4431
Epoch 50/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4420
Epoch 51/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4433
Epoch 52/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4424
Epoch 53/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4424
Epoch 54/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4430
Epoch 55/200
70/70 [==============================] - 2s 23ms/step - loss: 1.4403
Epoch 56/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4424
Epoch 57/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4423
Epoch 58/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4416
Epoch 59/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4388
Epoch 60/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4407
Epoch 61/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4434
Epoch 62/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4419
Epoch 63/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4407
Epoch 64/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4396
Epoch 65/200
70/70 [==============================] - 2s 23ms/step - loss: 1.4413
Epoch 66/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4404
Epoch 67/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4414
Epoch 68/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4404
Epoch 69/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4411
Epoch 70/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4418
Epoch 71/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4433
Epoch 72/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4405
Epoch 73/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4409
Epoch 74/200
70/70 [==============================] - 1s 21ms/step - loss: 1.4392
Epoch 75/200
70/70 [==============================] - 2s 21ms/step - loss: 1.4393
Epoch 76/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4376
Epoch 77/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4358
Epoch 78/200
70/70 [==============================] - 2s 22ms/step - loss: 1.4092
Epoch 79/200
70/70 [==============================] - 2s 22ms/step - loss: 1.2820
Epoch 80/200
70/70 [==============================] - 2s 22ms/step - loss: 1.1345
Epoch 81/200
70/70 [==============================] - 2s 22ms/step - loss: 1.1212
Epoch 82/200
70/70 [==============================] - 2s 22ms/step - loss: 1.1572
Epoch 83/200
70/70 [==============================] - 2s 22ms/step - loss: 1.1241
Epoch 84/200
70/70 [==============================] - 2s 22ms/step - loss: 1.1087
Epoch 85/200
70/70 [==============================] - 2s 22ms/step - loss: 1.1076
Epoch 86/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0953
Epoch 87/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0959
Epoch 88/200
70/70 [==============================] - 1s 21ms/step - loss: 1.0902
Epoch 89/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0784
Epoch 90/200
70/70 [==============================] - 2s 21ms/step - loss: 1.0795
Epoch 91/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0783
Epoch 92/200
70/70 [==============================] - 2s 21ms/step - loss: 1.0769
Epoch 93/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0664
Epoch 94/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0594
Epoch 95/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0721
Epoch 96/200
70/70 [==============================] - 1s 21ms/step - loss: 1.0632
Epoch 97/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0719
Epoch 98/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0522
Epoch 99/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0650
Epoch 100/200
70/70 [==============================] - 2s 21ms/step - loss: 1.0439
Epoch 101/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0465
Epoch 102/200
70/70 [==============================] - 1s 21ms/step - loss: 1.0412
Epoch 103/200
70/70 [==============================] - 2s 21ms/step - loss: 1.0407
Epoch 104/200
70/70 [==============================] - 1s 21ms/step - loss: 1.0429
Epoch 105/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0411
Epoch 106/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0383
Epoch 107/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0357
Epoch 108/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0165
Epoch 109/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0312
Epoch 110/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0077
Epoch 111/200
70/70 [==============================] - 2s 21ms/step - loss: 1.0085
Epoch 112/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0080
Epoch 113/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0136
Epoch 114/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0030
Epoch 115/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0089
Epoch 116/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0032
Epoch 117/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9969
Epoch 118/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0040
Epoch 119/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0016
Epoch 120/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9967
Epoch 121/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0060
Epoch 122/200
70/70 [==============================] - 2s 21ms/step - loss: 1.0003
Epoch 123/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9931
Epoch 124/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9933
Epoch 125/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9958
Epoch 126/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9921
Epoch 127/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0039
Epoch 128/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9762
Epoch 129/200
70/70 [==============================] - 2s 22ms/step - loss: 1.0061
Epoch 130/200
70/70 [==============================] - 2s 23ms/step - loss: 0.9759
Epoch 131/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9689
Epoch 132/200
70/70 [==============================] - 2s 21ms/step - loss: 0.9753
Epoch 133/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9632
Epoch 134/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9722
Epoch 135/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9593
Epoch 136/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9484
Epoch 137/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9439
Epoch 138/200
70/70 [==============================] - 1s 21ms/step - loss: 0.9668
Epoch 139/200
70/70 [==============================] - 1s 21ms/step - loss: 0.9345
Epoch 140/200
70/70 [==============================] - 2s 21ms/step - loss: 0.9300
Epoch 141/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9289
Epoch 142/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9254
Epoch 143/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9197
Epoch 144/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9265
Epoch 145/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9286
Epoch 146/200
70/70 [==============================] - 2s 21ms/step - loss: 0.9227
Epoch 147/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9235
Epoch 148/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9067
Epoch 149/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9158
Epoch 150/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9049
Epoch 151/200
70/70 [==============================] - 2s 23ms/step - loss: 0.9168
Epoch 152/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8974
Epoch 153/200
70/70 [==============================] - 2s 21ms/step - loss: 0.9042
Epoch 154/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8915
Epoch 155/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9135
Epoch 156/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8990
Epoch 157/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9047
Epoch 158/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9024
Epoch 159/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8840
Epoch 160/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8856
Epoch 161/200
70/70 [==============================] - 2s 21ms/step - loss: 1.1273
Epoch 162/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9594
Epoch 163/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9314
Epoch 164/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9172
Epoch 165/200
70/70 [==============================] - 2s 22ms/step - loss: 0.9048
Epoch 166/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8991
Epoch 167/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8846
Epoch 168/200
70/70 [==============================] - 1s 21ms/step - loss: 0.8701
Epoch 169/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8906
Epoch 170/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8648
Epoch 171/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8941
Epoch 172/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8820
Epoch 173/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8862
Epoch 174/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8866
Epoch 175/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8531
Epoch 176/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8588
Epoch 177/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8520
Epoch 178/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8541:
Epoch 179/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8476
Epoch 180/200
70/70 [==============================] - 1s 21ms/step - loss: 0.8608
Epoch 181/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8339
Epoch 182/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8356
Epoch 183/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8451
Epoch 184/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8605
Epoch 185/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8558
Epoch 186/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8345
Epoch 187/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8346
Epoch 188/200
70/70 [==============================] - 1s 21ms/step - loss: 0.8481
Epoch 189/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8189
Epoch 190/200
70/70 [==============================] - 2s 21ms/step - loss: 0.8232
Epoch 191/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8477
Epoch 192/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8491
Epoch 193/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8233
Epoch 194/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8087
Epoch 195/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8299
Epoch 196/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8165
Epoch 197/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8194
Epoch 198/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8179
Epoch 199/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8146
Epoch 200/200
70/70 [==============================] - 2s 22ms/step - loss: 0.8340

In [189]:
# Applying same train functions for test data
test_data = scaled_data_close[training_data_len:, :]
X_test = []
Y_test = []

# Accessin X_test,Y_test
for i in range(60,len(test_data)):
    X_test.append(test_data[i-60:i, 0])
    Y_test.append(test_data[i])

# Converting them to array
X_test, Y_test = np.array(X_test), np.array(Y_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

In [197]:
# Model Predictions
preds = model.predict(X_test)

In [198]:
# Finding RMSE Value
mse = mean_squared_error(Y_test, preds)

In [199]:
# Saving predicted results inot Dataframe
train = pd.DataFrame(scaled_data_close[:training_data_len],columns = ["Close"])
valid = pd.DataFrame(scaled_data_close[training_data_len+60:],columns = ["Close"])
preds = [round(i,2) for i in list(preds.ravel())]
valid['Predictions'] = preds

In [200]:
# Converting the data into structured way
df_pred = pd.DataFrame()
for i,j in enumerate(range(48)):
    df_pred[i] = list(preds[60:60+30])
    i = i+30
    
# Create Date Column for predictions
date_list = []
for i,j in enumerate(range(14,44)):
    if j > 30:
        j = j-30
        date_list.append(str(j)+"-12-2021")
    else:
        date_list.append(str(j)+"-11-2021")

# Inserting Date column at 0th index
df_pred.insert(loc=0, column='Date', value=date_list)

In [201]:
# Renaming Columns
df_pred.columns = df_weather_copy.columns

In [202]:
# Predicted Data
df_pred

,READING DATE,00:30,01:00,01:30,02:00,02:30,03:00,03:30,04:00,04:30,...,19:30,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,23:59:00
0,14-11-2021,2.08,2.08,2.08,2.08,2.08,2.08,2.08,2.08,2.08,...,2.08,2.08,2.08,2.08,2.08,2.08,2.08,2.08,2.08,2.08
1,15-11-2021,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,...,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99
2,16-11-2021,1.88,1.88,1.88,1.88,1.88,1.88,1.88,1.88,1.88,...,1.88,1.88,1.88,1.88,1.88,1.88,1.88,1.88,1.88,1.88
3,17-11-2021,1.69,1.69,1.69,1.69,1.69,1.69,1.69,1.69,1.69,...,1.69,1.69,1.69,1.69,1.69,1.69,1.69,1.69,1.69,1.69
4,18-11-2021,1.47,1.47,1.47,1.47,1.47,1.47,1.47,1.47,1.47,...,1.47,1.47,1.47,1.47,1.47,1.47,1.47,1.47,1.47,1.47
5,19-11-2021,1.17,1.17,1.17,1.17,1.17,1.17,1.17,1.17,1.17,...,1.17,1.17,1.17,1.17,1.17,1.17,1.17,1.17,1.17,1.17
6,20-11-2021,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.98,...,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.98,0.98
7,21-11-2021,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,...,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85
8,22-11-2021,0.82,0.82,0.82,0.82,0.82,0.82,0.82,0.82,0.82,...,0.82,0.82,0.82,0.82,0.82,0.82,0.82,0.82,0.82,0.82
9,23-11-2021,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,...,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79
10,24-11-2021,0.78,0.78,0.78,0.78,0.78,0.78,0.78,0.78,0.78,...,0.78,0.78,0.78,0.78,0.78,0.78,0.78,0.78,0.78,0.78
11,25-11-2021,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,...,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77
12,26-11-2021,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,...,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77
13,27-11-2021,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,...,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77
14,28-11-2021,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,...,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77,0.77
15,29-11-2021,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,...,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79,0.79
16,30-11-2021,0.81,0.81,0.81,0.81,0.81,0.81,0.81,0.81,0.81,...,0.81,0.81,0.81,0.81,0.81,0.81,0.81,0.81,0.81,0.81
17,1-12-2021,0.90,0.90,0.90,0.90,0.90,0.90,0.90,0.90,0.90,...,0.90,0.90,0.90,0.90,0.90,0.90,0.90,0.90,0.90,0.90
18,2-12-2021,1.10,1.10,1.10,1.10,1.10,1.10,1.10,1.10,1.10,...,1.10,1.10,1.10,1.10,1.10,1.10,1.10,1.10,1.10,1.10
19,3-12-2021,1.61,1.61,1.61,1.61,1.61,1.61,1.61,1.61,1.61,...,1.61,1.61,1.61,1.61,1.61,1.61,1.61,1.61,1.61,1.61
20,4-12-2021,1.98,1.98,1.98,1.98,1.98,1.98,1.98,1.98,1.98,...,1.98,1.98,1.98,1.98,1.98,1.98,1.98,1.98,1.98,1.98
21,5-12-2021,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,...,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00
22,6-12-2021,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,...,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00
23,7-12-2021,2.13,2.13,2.13,2.13,2.13,2.13,2.13,2.13,2.13,...,2.13,2.13,2.13,2.13,2.13,2.13,2.13,2.13,2.13,2.13
24,8-12-2021,2.10,2.10,2.10,2.10,2.10,2.10,2.10,2.10,2.10,...,2.10,2.10,2.10,2.10,2.10,2.10,2.10,2.10,2.10,2.10
25,9-12-2021,2.06,2.06,2.06,2.06,2.06,2.06,2.06,2.06,2.06,...,2.06,2.06,2.06,2.06,2.06,2.06,2.06,2.06,2.06,2.06
26,10-12-2021,1.94,1.94,1.94,1.94,1.94,1.94,1.94,1.94,1.94,...,1.94,1.94,1.94,1.94,1.94,1.94,1.94,1.94,1.94,1.94
27,11-12-2021,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,...,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75
28,12-12-2021,1.48,1.48,1.48,1.48,1.48,1.48,1.48,1.48,1.48,...,1.48,1.48,1.48,1.48,1.48,1.48,1.48,1.48,1.48,1.48
29,13-12-2021,1.23,1.23,1.23,1.23,1.23,1.23,1.23,1.23,1.23,...,1.23,1.23,1.23,1.23,1.23,1.23,1.23,1.23,1.23,1.23

In [203]:
# MSE Value
print("MSE Value",mse)

MSE Value 2.438482986484441

In [204]:
df_pred.to_csv("14112021_13122021_PowerConsumptionPrediction",index=False)